config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :pictures do
    collection do
      post :confirm
    end
    member do
      get :favorite
    end
    resources :comments
  end

  resources :users do
    member do
      get :favorite
    end
    member do
      get :relationship
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?

  resources :relationships, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # コメントを保存、投稿するためのアクションです。
  before_action :set_picture, only: [:create, :edit, :update]
  def create
    # pictureをパラメータの値から探し出し,pictureに紐づくcommentsとしてbuildします。
    @comment = @picture.comments.build(comment_params) #@pictureのidをpicture_idに含んだ状態のCommentインスタンスをnew(作成)
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.js { render :index } #index.js.erbへrender
      else
        format.html { redirect_to picture_path(@picture), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @comment = @picture.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @picture.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end
  private
  # ストロングパラメーター
  def comment_params
    params.require(:comment).permit(:picture_id, :content)
  end
  def set_picture
    @picture = Picture.find(params[:picture_id])
  end
end

app/views/comments/_edit.html.erb
<%= form_with(model: [picture, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{picture.id}" %>
    <%= form.label :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<!-- この記述がpictureのshow画面に表示されるコメント入力欄になります -->
<%= form_with(model: [picture, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, :placeholder => " ex) Nice!" %>
  </div>
  <div class="actions">
    <%= form.submit "Comment!" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li class="comment">
        <p><%= comment.content %></p><br>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <p><%= link_to "✎", edit_picture_comment_path(picture, comment), remote: true %></p>
        <p><%= link_to "×", picture_comment_path(comment.picture_id, comment.id), method: :delete, remote: true,
                                        data: { confirm: "本当に削除しますか?"} %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', picture: @picture, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.picture.comments, picture: @comment.picture }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");