config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :pictures do
    collection do
      post :confirm
    end
    member do
      get :favorite
    end
    resources :comments
  end

  resources :users do
    member do
      get :favorite
    end
    member do
      get :relationship
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?

  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
    has_many :pictures, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_pictures, through: :favorites, source: :picture
    has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
    has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    mount_uploader :image_name, IconUploader

    #指定のユーザをフォローする
    def follow!(other_user)
        active_relationships.create!(followed_id: other_user.id)
    end

    #指定のユーザのフォローを解除する
    def unfollow!(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end

    #フォローしているかどうかを確認する
    def following?(other_user)
        active_relationships.find_by(followed_id: other_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy favorite relationship]
  skip_before_action :login_required, only: [:new, :create]
  before_action :already_logged_in, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @following = @user.following
    @followers = @user.followers
  end

  def new
    @user = User.new
  end
  def favorite
    
  end

  def relationship
    @following = @user.following
    @followers = @user.followers
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Your account was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Your account was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_path, notice: "Your account was successfully destroyed."
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image_name, :image_name_cache)
  end
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id))  do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "Follow!" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "Unfollow.." %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :image_name %>
      <% if user.image_name.present? %>
        <%= image_tag user.image_name.url %>
      <% end %>
      <%= form.file_field :image_name, class: "filefield" %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
      <p>*Password must be at least 6 characters long.</p>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
      <p>*Enter your password again for verification.</p>
    </div>

    <div class="actions">
      <%= form.submit "Create my account" %>
    </div>
    <br>
    <% unless logged_in? %>
      <div>
        Already have an account? <%= link_to "Log in here", new_session_path %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form', user: @user %>

<p class="bottom"><%= link_to 'Back', @user %></p>

app/views/users/favorite.html.erb
<h1><%= @user.name%>'s Favorites</h1>
<div class="container">
  <div class="row">
    <% @user.favorite_pictures.order(created_at: :desc).each do |picture| %>
      <div class="col-xs-4">
        <%= link_to (image_tag picture.image.url), picture, class: "userposts"%>
      </div>
    <% end %> 
  </div>
</div>

<p class="bottom"><%= link_to 'Back', @user %></p>

app/views/users/index.html.erb
 <h1>Users</h1>
 <table>
  <% @users.each do |user| %>
  <tr>
    <td>
      <%= image_tag user.image_name.url , class: "icon" %>
      <%= link_to user.name, user %>
      <%= link_to '💌', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
    </td>
    <!---フォローボタンのパーシャル _follow_form.html.erb --->
    <td><%= render 'follow_form', user: user %></td>
  </tr>
  <% end %>
  </table> 

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign up</h1><br>
<p>Welcome to Instagram!</p>

<%= render 'form', user: @user %>

app/views/users/relationship.html.erb
<h1><%= @user.name%>'s relationship</h1>
<table>
  <td colspan="2">following</td>
  <% @following.each do |user| %>
  <tr>
    <td>
      <%= image_tag user.image_name.url , class: "icon" %>
      <%= link_to user.name, user %>
      <%= link_to '💌', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
    </td>
    <!---フォローボタンのパーシャル _follow_form.html.erb --->
    <td><%= render 'follow_form', user: user %></td>
  </tr>
  <% end %>
</table>
<table>
  <td colspan="2">followers</td>
  <% @followers.each do |user| %>
  <tr>
    <td>
      <%= image_tag user.image_name.url , class: "icon" %>
      <%= link_to user.name, user %>
      <%= link_to '💌', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
    </td>
    <!---フォローボタンのパーシャル _follow_form.html.erb --->
    <td><%= render 'follow_form', user: user %></td>
  </tr>
  <% end %>
  </table> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>About</h1>
<div class="aboutarea">
  <div class="row">
    <div class="col-sm-6 about">
      <%= image_tag @user.image_name.url, class: "profile"%> <br>
      <p>
        <%= link_to relationship_user_path(@user) do %>
            <%= @following.count %> following |
        <% end %> 
        <%= link_to relationship_user_path(@user) do %>
            <%= pluralize(@followers.count, "follower", locale: :en) %>
        <% end %>
      </p>
    </div>

    <div class="col-sm-6 about">
      <p><strong>Name:</strong>
        <%= @user.name %>
      </p>
      <p><strong>Email:</strong>
      <%= @user.email %>
      <% if Rails.env.development? %>
        <%= link_to letter_opener_web_path do %>
          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        <% end %>
      <% end %>
      </p>
      <p>
        <%= pluralize(@user.pictures.count, "post", locale: :en) %> |
        <%= link_to favorite_user_path(@user) do %>
          <%= pluralize(@user.favorite_pictures.count, "like", locale: :en) %>
        <% end %> 
      </p>
      <p>
        <%= link_to 'Edit Profile', edit_user_path(@user) %> |
        <%= link_to 'Delete Your Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
      
    </div>
  </div>
</div>

<h1><%= @user.name%>'s Posts</h1>
<div class="container">
  <div class="row">
    <% @user.pictures.order(created_at: :desc).each do |picture| %>
      <div class="col-sm-4">
        <%= link_to (image_tag picture.image.url), picture, class: "userposts" if picture.image.present?%>
      </div>
    <% end %> 
  </div>
</div>