config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :pictures do
    collection do
      post :confirm
    end
    member do
      get :favorite
    end
    resources :comments
  end

  resources :users do
    member do
      get :favorite
    end
    member do
      get :relationship
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?

  resources :relationships, only: [:create, :destroy]

end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy

  # validates :image,  presence: true
  validates :content, presence: true, length: { maximum: 255 }

  mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy favorite ]
  skip_before_action :login_required, only: [:index, :show]
  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    @comments = @picture.comments
    @comment = @picture.comments.build
  end

  def favorite
 
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
    redirect_to pictures_path unless same_user?
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      PostMailer.post_mailer(@picture).deliver
      redirect_to @picture, notice: "Your post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def update
    if @picture.update(picture_params)
      redirect_to @picture, notice: "Your post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_url, notice: "Your post was successfully deleted."
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content, :user_id)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
          confirm_pictures_path
        elsif action_name == 'edit'
          picture_path
        end
    end
    def authenticate_user?(picture)
      picture.user_id == current_user.id
    end
end

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url:choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <%= form.file_field :image, class: "filefield" %>
      <%= form.hidden_field :image_cache %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>Confirmation</h1>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <div class="form">
  <p>Are you sure you want to publish this post?</p><br>
    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :content%>
    </div>
    <div class="field">
      <%= form.label :content %>
      <p><%= @picture.content %></p>
    </div>
    
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <div class="form">
    <div class="field">
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :content%>
    </div>
    <div class="actions">
      <%= form.submit "Back", name: "back" %>
    </div>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', picture: @picture %>


<p class="bottom"><%= link_to 'Delete this picture', @picture, method: :delete, data: { confirm: 'Are you sure?' } %></p>

app/views/pictures/favorite.html.erb
<h1>Favorite</h1>
    <br>
    <p>
      <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> <%= pluralize(@picture.favorites.count, "like", locale: :en)%>
    </p>
  <table class="favorite">
    <tr>
      <td><strong>Liked by...</strong></td>
    </tr>
    <% if @picture.favorite_users.present? %>
        <% @picture.favorite_users.each do |favorite| %>
          <tr><td><%= image_tag favorite.image_name.url , class: "icon" %> <%= favorite.name %></td></tr>
        <% end %>
    <% end %>
     
  </table>

<p class="bottom"><%= link_to 'Back', pictures_path %></p>


  

  

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Recent Posts</h1>

<table>
  
    <% @pictures.each do |picture| %>
    <tbody>
      <tr>
        <td class="name">
          <%= image_tag picture.user.image_name.url , class: "icon" %> 
          <strong><%= picture.user.name %></td></strong>
      </tr>
      <tr>
        <td><%= link_to (image_tag picture.image.url), picture  if picture.image.present?%></td>
      </tr>
      <tr>
        <td><%= picture.content %></td>
      </tr>
      <tr>
        <td>
          <%= link_to favorite_picture_path(picture.id) do %>
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> <%= pluralize(picture.favorites.count, "like", locale: :en)%>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          | <%= picture.created_at.strftime('%Y/%m/%d %H:%M')%> |
          <% if logged_in? && authenticate_user?(picture) %>
            <%= link_to edit_picture_path(picture) do %>
              <span class="glyphicon glyphicon-option-horizontal" aria-hidden="true"></span>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tbody>  
    <% end %>
</table>

app/views/pictures/new.html.erb
<h1>New Post</h1>

<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Detail</h1>
  <table class="detail">
    <tr>
      <td><strong>User:</strong></td>
      <td><%= @picture.user.name %></td>
      <td colspan="4"></td>
    </tr>
    <tr>
      <td><strong>Image:</strong></td>
      <td><%= image_tag @picture.image.url if @picture.image.present?%></td>
    </tr>
    <tr>
      <td><strong>Content:</strong></td>
      <td><%= @picture.content %></td>
    </tr>
    <tr>
      <td><strong>Posted at:</strong></td>
      <td><%= @picture.created_at.strftime('%Y/%m/%d %H:%M')%></td>
    </tr>
  </table>

  <p>
    <%= link_to favorite_picture_path(@picture.id) do %>
      <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> <%= pluralize(@picture.favorites.count, "like", locale: :en)%>
    <% end %>
  </p>

  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'いいね解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to 'いいねする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-danger' %>
    <% end %>
  <% end %>

<!-- コメント一覧（ここから下の内容が重要） -->
<div class="comment_area">
  <p>Comments</p>
  <!-- このcomments_areaというHTMLのidを取得して、このdivの中にあるHTMLの要素をJavaScript（Ajax）で書き換え -->
  <div id="comments_area">
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender パーシャルを表示 comments/_index.html.erb -->
    <%= render partial: 'comments/index', locals: { comments: @comments, picture: @picture } %>
  </div>
  <!-- コメント入力欄をブログの詳細ページに表示するためのrender パーシャルを表示 comments/_form.html.erb -->
  <%= render partial: 'comments/form', locals: { comment: @comment, picture: @picture } %>
</div>

<% if logged_in? && authenticate_user?(@picture) %>
  <p>
    <%= link_to edit_picture_path(@picture) do %>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true">Edit</span>
    <% end %> |
    <%= button_to @picture, method: :delete do %>
    <span class="glyphicon glyphicon-trash" aria-hidden="true">Delete</span>
    <% end %>
  </p>
<% end %>

<p class="bottom"><%= link_to 'Back', pictures_path %></p>