config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :pictures do
    collection do
      post :confirm
    end
    member do
      get :favorite
    end
    resources :comments
  end

  resources :users do
    member do
      get :favorite
    end
    member do
      get :relationship
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?

  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header><%= link_to "InstagramClone", pictures_path %></header>
        <ul class="nav justify-content-center">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'Users', users_path, class: "nav-link active"%>
          </li>
          <li class="nav-item">
            <%= link_to "New Post", new_picture_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Talk', conversations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", session_path(current_user.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link'%>
          </li>
        <% else %>
          <li class="nav-item"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span></li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_session_path %>
          </li>
          <li class="nav-item"><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></li>
        <% end %>
        </ul>
        <% if logged_in? %>
          <p class="login">Logged in as <strong> <%= link_to current_user.name, user_path(current_user.id) %></strong></p>
        <% end %>
        <%= yield %>
        <footer><p>Copyright ©︎ 2021 DIVE INC ALL RIGHTS RESERVED.</p></footer>
    </div>
  </body>
</html>